import type { Metadata } from 'next';
import './app.css';
import { ThemeProvider } from '@/components/theme-provider';

export const metadata: Metadata = {
  title: 'Royals',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      // Note: the focus-visible polyfill adds additional atstributes to `html`
      // that cause hydration mismatch
      lang='en'
      suppressHydrationWarning
      data-color-mode='light'
      data-light-theme='light'
    >
      <head>
        <link rel='preconnect' href='https://rsms.me/' />
        <link rel='stylesheet' href='https://rsms.me/inter/inter.css'></link>
      </head>
      <body className='antialiased'>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
